routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

Route::middleware('auth')->group(function () {

    Route::get('/', function () {
        return redirect('/apps');
    })->name('welcome');

    Route::get('/home', function () {
        return redirect('/apps');
    })->name('home');

    //Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('projects', App\Http\Controllers\ProjectController::class);
    Route::resource('users', App\Http\Controllers\UserController::class);
    Route::resource('subProjects', App\Http\Controllers\SubProjectController::class);
    Route::resource('slides', App\Http\Controllers\SlideController::class);
    Route::resource('slideItems', App\Http\Controllers\SlideItemController::class);
    Route::resource('realisations', App\Http\Controllers\RealisationController::class);
    Route::resource('partners', App\Http\Controllers\PartnerController::class);
    Route::resource('apps', App\Http\Controllers\AppController::class);
    Route::resource('slideItems', App\Http\Controllers\SlideItemController::class);
    Route::resource('subProjects', App\Http\Controllers\SubProjectController::class);
    Route::resource('faqs', App\Http\Controllers\FaqController::class);
    Route::resource('newsletters', App\Http\Controllers\NewsletterController::class);
    Route::resource('notifications', App\Http\Controllers\NotificationController::class);
    Route::resource('contacts', App\Http\Controllers\ContactController::class);
    Route::resource('quotes', App\Http\Controllers\QuoteController::class);
    Route::resource('reviews', App\Http\Controllers\ReviewController::class);
});

resources/views/apps/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Créer une application</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'apps.store', 'files' => true]) !!}

            <div class="card-body">

                <div class="row">
                    @include('apps.fields', ['status' => \App\Models\User::getStatus(null)])
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Enrégistrer', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('apps.index') }}" class="btn btn-default">Annuler</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/apps/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Modification d'application</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($app, ['route' => ['apps.update', $app->id], 'method' => 'patch', 'files' => true]) !!}

            <div class="card-body">
                <div class="row">
                    @include('apps.fields', ['status' => \App\Models\User::getStatus($app)])
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Modifier', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('apps.index') }}" class="btn btn-default">Annuler</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/apps/fields.blade.php
<!-- Libelle Field -->
<div class="form-group col-sm-5">
    {!! Form::label('libelle', 'Nom:') !!}
    {!! Form::text('libelle', null, ['class' => 'form-control']) !!}
</div>
<!-- Ordre Field -->
<div class="form-group col-sm-2">
    {!! Form::label('ordre', 'Ordre:') !!}
    {!! Form::number('ordre', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-2">

    {!! Form::label('status', 'Status') !!}
    {!! Form::select('status', $status, null, ['class' => 'form-control']) !!}
</div>

{!! Form::number('id', null, ['class' => 'form-control','hidden' => true]) !!}

<!-- Image Field -->
<div class="form-group col-sm-3">
    {!! Form::label('image', 'Logo:') !!}
    <div class="input-group">
        <div class="custom-file">
            {!! Form::file('image', ['class' => 'custom-file-input']) !!}
            {!! Form::label('image', 'Choisir la photo', ['class' => 'custom-file-label']) !!}
        </div>
    </div>
</div>



<!-- Email Field -->
<div class="form-group col-sm-3">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-3">
    {!! Form::label('phone1', 'Téléphone 1:') !!}
    {!! Form::text('phone1', null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-3">
    {!! Form::label('phone2', 'Téléphone 2:') !!}
    {!! Form::text('phone2', null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-3">
    {!! Form::label('phone3', 'Téléphone 3:') !!}
    {!! Form::text('phone3', null, ['class' => 'form-control']) !!}
</div>

<!-- Map Field -->
<div class="form-group col-sm-6">
    {!! Form::label('map', 'Lien google map:') !!}
    {!! Form::text('map', null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-6">
    {!! Form::label('address', 'Adresse:') !!}
    {!! Form::text('address', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<div class="clearfix"></div>

resources/views/apps/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Liste des applications</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('apps.create') }}">
                        Ajouter
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('apps.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/apps/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Détail application</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('apps.index') }}">
                        Retour
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('apps.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/apps/show_fields.blade.php
<!-- Libelle Field -->
<div class="col-sm-12">
    <p>{!! Form::label('libelle', 'Nom: ') !!} {{ $app->libelle }}</p>
</div>

<!-- Description Field -->
<div class="col-sm-12">
    <p>{!! Form::label('description', 'Description: ') !!} {{ $app->description }}</p>
</div>

<!-- Ordre Field -->
<div class="col-sm-12">
    <p>{!! Form::label('ordre', 'Ordre: ') !!} {{ $app->ordre }}</p>
</div>

<!-- Status Field -->
<div class="col-sm-12">
    <p>{!! Form::label('status', 'Status: ') !!} {{ $app->status == true ? "Activé" : "Désactivé"  }}</p>
</div>

<!-- User Id Field -->
<div class="col-sm-12">
    <p>{!! Form::label('user_id', 'Createur: ') !!} {{ $app->user ? $app->user->email : $app->user_id }}</p>
</div>

<!-- Map Field -->
<div class="col-sm-12">
    <p>{!! Form::label('map', 'Lien map:') !!} {{ $app->map }}</p>
</div>

<!-- Email Field -->
<div class="col-sm-12">
    <p>{!! Form::label('email', 'Email:') !!} {{ $app->email }}</p>
</div>

<!-- Address Field -->
<div class="col-sm-12">
    <p>{!! Form::label('address', 'Address:') !!} {{ $app->address }}</p>
</div>

<!-- Phone1 Field -->
<div class="col-sm-12">
    <p>{!! Form::label('phone1', 'Phone1:') !!} {{ $app->phone1 }}</p>
</div>

<!-- Phone2 Field -->
<div class="col-sm-12">
    <p>{!! Form::label('phone2', 'Phone2:') !!} {{ $app->phone2 }}</p>
</div>

<!-- Phone3 Field -->
<div class="col-sm-12">
    <p>{!! Form::label('phone3', 'Phone3:') !!} {{ $app->phone3 }}</p>
</div>

<!-- Image Field -->
<div class="col-sm-12">
    <p>{!! Form::label('image', 'Logo: ') !!}<img  src="{{ image_url($app->image) }}" alt="" class="img-fluid" style="width:200px; height: 200px"></p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    <p>{!! Form::label('created_at', 'Date: ') !!} {{ $app->created_at->format('d M. Y') }}</p>
</div>

resources/views/apps/table.blade.php
<div class="table-responsive">
    <table class="table" id="apps-table">
        <thead>
        <tr>
        <th>Nom</th>
        <th>email</th>
        <th>Téléphone</th>
        <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($apps as $app)
            <tr>
            <td><img  src="{{ image_url($app->image) }}" alt="" class="user-image img-circle elevation-2" style="width:20px; height: 20px"> {{ $app->libelle }}</td>
            <td>{{ $app->email }}</td>
            <td>{{ $app->phone1 }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['apps.destroy', $app->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('apps.show', [$app->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('apps.edit', [$app->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>